### ISSUE TITLE
AttributeError: HLS instance has no attribute 'representations'

### ISSUE THREAD

**Issue by likai1993** [Eyevinn/hls-to-dash#5]
In my practice, when using such command,it throws following error:
hls-to-dash "http://10.47.235.113:8001/local/hls/content/00000000020000000022_,1,2,.mp4.urlset/index.m3u8"  > stream.mpd

AttributeError: HLS instance has no attribute 'representations'

index.m3u8 list:
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1263919,RESOLUTION=1280x720,FRAME-RATE=25.000,CODECS="avc1.640029,mp4a.40.2"
1-f1-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1195925,RESOLUTION=1104x622,FRAME-RATE=50.000,CODECS="avc1.64001f,mp4a.40.2"
1-f2-v1-a1.m3u8

**Comment by birme** [comment]
Thanks for the report. I will look into it

**Comment by sgermain06** [comment]
I'm having the same problem.

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=200000,CODECS="avc1.4d001f,mp4a.40.2",RESOLUTION=960x540
test.m3u8

**Comment by z3cka** [comment]
Me too.
```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: no-cache
Content-Length: 150
Content-Type: application/vnd.apple.mpegurl
Date: Sat, 19 Aug 2017 17:38:57 GMT
Server: FlashCom/3.5.7

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=600560,CODECS="avc1.100.30, mp4a.40.2",RESOLUTION=568x426
chunklist_w352230527.m3u8
```
Is it something with my HLS source?

**Comment by birme** [comment]
Hi,

If mediastreamvalidator says it is a valid stream it is probably a bug in the HLS parseing. Will have a look if I get some time next week.

Best regards,
    Jonas

**Comment by kjellc** [comment]
Hello,
I'm trying to reproduce this issue but the URL supplied above (by RecareLee) does not work.
Anyone has a working URL I can use?

**Comment by yogeshkm** [comment]
Hi,
This issue is not fixed in the fix as I see: 

hls-to-dash https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8 --debug
Restoring context from /tmp/m3u8s.ctx
Context: timebase=90000
Loading playlist:  https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8
Parsing master playlist
Traceback (most recent call last):
  File "/usr/local/bin/hls-to-dash", line 9, in <module>
    load_entry_point('hls2dash==0.2.2', 'console_scripts', 'hls-to-dash')()
  File "build/bdist.linux-x86_64/egg/hls2dash/__init__.py", line 36, in main
  File "build/bdist.linux-x86_64/egg/hls2dash/lib/MPD.py", line 234, in load
  File "build/bdist.linux-x86_64/egg/hls2dash/lib/MPD.py", line 416, in _parseMaster
  File "build/bdist.linux-x86_64/egg/hls2dash/lib/MPD.py", line 250, in _profileFromFilename
AttributeError: HLS instance has no attribute 'representations'

**Comment by Brainiarc7** [comment]
Hello,

The patchwork above has yet to be merged. 

See https://github.com/Eyevinn/hls-to-dash/pull/6
